# Generated by Django 3.2.13 on 2022-06-13 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerprofile',
            name='sessions',
        ),
    ]
