# Generated by Django 3.2.13 on 2022-06-13 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('volunteer_dashboard', '0002_remove_volunteerprofile_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
