# Generated by Django 3.2.13 on 2022-06-13 22:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_dashboard', '0003_volunteerprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerprofile',
            name='photo',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
