# Generated by Django 3.2.13 on 2022-06-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_dashboard', '0006_remove_volunteerprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='name',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
