# Generated by Django 3.2.13 on 2022-06-11 13:00

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('full', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('photo', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, null=True, verbose_name='image')),
                ('bio', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('sessions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='volunteer_app.session')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='volunteers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='volunteer_app.volunteerprofile'),
        ),
    ]
