# Generated by Django 3.2.13 on 2022-06-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
    ]
