# Generated by Django 3.2.13 on 2022-06-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_app', '0002_volunteerprofile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='volunteers',
        ),
        migrations.AddField(
            model_name='session',
            name='volunteers',
            field=models.ManyToManyField(null=True, to='volunteer_app.VolunteerProfile'),
        ),
    ]
