# Generated by Django 3.2.13 on 2022-06-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_app', '0003_auto_20220611_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='volunteers',
            field=models.ManyToManyField(to='volunteer_app.VolunteerProfile'),
        ),
        migrations.RemoveField(
            model_name='volunteerprofile',
            name='sessions',
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='sessions',
            field=models.ManyToManyField(to='volunteer_app.Session'),
        ),
    ]
