# Generated by Django 3.2.13 on 2022-06-11 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_app', '0004_auto_20220611_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='full',
            new_name='status',
        ),
    ]
