# Generated by Django 3.2.13 on 2022-06-11 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_app', '0005_rename_full_session_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='volunteers',
        ),
        migrations.AddField(
            model_name='session',
            name='volunteers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='volunteer_app.volunteerprofile'),
        ),
    ]
